import React, { useEffect, useRef, useState } from "react";
import { createRoot } from "react-dom/client";
import {
  Piano,
  ArrowUpRight,
  Play,
  Upload,
  Mic,
  Cable,
  Check,
  Music2,
  Download,
  CircleHelp,
  Square,
  Table2,
  Moon,
  Sun,
  Trash2,
} from "lucide-react";
import "./style.css";
import demo from "./demo.json";
import Results from "./Results.jsx";
import {
  permissionRequest,
  startAudioRecording,
  startMidiCapture,
} from "./capture.js";

const API = import.meta.env.VITE_API_URL || "";
const demoReference = demo.notes.map((n) => ({
  pitch: n.pitch,
  start: n.time,
  duration: 0.38,
}));
// Browser demo is a bundled, disclosed snapshot. Real uploads always use Python.
async function request(path, options) {
  let res;
  try {
    res = await fetch(API + path, options);
  } catch {
    throw Error(
      "The Python server could not be reached. Start it on port 8000 and try again.",
    );
  }
  let data;
  try {
    data = await res.json();
  } catch {
    throw Error(
      "The server did not return a report. Check that the Python server is running.",
    );
  }
  if (!res.ok)
    throw Error(
      typeof data.detail === "string"
        ? data.detail
        : "The input was rejected. Check the files and try a shorter passage.",
    );
  return data;
}

function App() {
  const [result, setResult] = useState(demo),
    [mode, setMode] = useState("midi"),
    [tab, setTab] = useState("overview"),
    [busy, setBusy] = useState(false),
    [error, setError] = useState(""),
    [reference, setReference] = useState(null),
    [performance, setPerformance] = useState(null),
    [selected, setSelected] = useState(null),
    [recording, setRecording] = useState(false),
    [midiDevice, setMidiDevice] = useState(""),
    [captureCount, setCaptureCount] = useState(0),
    [playing, setPlaying] = useState(false),
    [info, setInfo] = useState(false),
    [connecting, setConnecting] = useState(false),
    [notice, setNotice] = useState(""),
    [exportUrl, setExportUrl] = useState(""),
    [theme, setTheme] = useState(
      () =>
        localStorage.getItem("cadence-theme") ||
        (matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light"),
    );
  useEffect(() => {
    document.documentElement.dataset.theme = theme;
    localStorage.setItem("cadence-theme", theme);
  }, [theme]);
  const audioCtx = useRef(null),
    reportDialog = useRef(null),
    recorder = useRef(null),
    midiAccess = useRef(null),
    midiCapture = useRef(null),
    capturing = useRef(false),
    audioTimer = useRef(null),
    midiTimer = useRef(null);
  useEffect(
    () => () => {
      recorder.current?.stop();
      midiCapture.current?.stop();
      if (audioCtx.current && audioCtx.current.state !== "closed")
        audioCtx.current.close();
      clearTimeout(audioTimer.current);
      clearTimeout(midiTimer.current);
    },
    [],
  );
  useEffect(
    () => () => {
      if (exportUrl) URL.revokeObjectURL(exportUrl);
    },
    [exportUrl],
  );
  async function runDemo() {
    setBusy(true);
    setError("");
    setNotice("");
    try {
      setResult(await request("/api/demo"));
    } catch {
      setResult(demo);
      setNotice(
        "The Python server is offline. These are saved demo results generated by Python.",
      );
    } finally {
      setBusy(false);
      setSelected(null);
    }
  }
  async function analyzeUpload(e) {
    e.preventDefault();
    setError("");
    if (!reference || !performance) {
      setError("Choose a reference MIDI and a performance first.");
      return;
    }
    setBusy(true);
    setNotice("");
    try {
      const data = new FormData();
      data.append("reference", reference);
      data.append("performance", performance);
      setResult(await request("/api/analyze", { method: "POST", body: data }));
      setSelected(null);
    } catch (e) {
      setError(
        e.message.includes("fetch")
          ? "Backend is offline. Start the Python server to analyze files."
          : e.message,
      );
    } finally {
      setBusy(false);
    }
  }
  async function stopAudio() {
    clearTimeout(audioTimer.current);
    const file = await recorder.current?.stop();
    recorder.current = null;
    if (file) setPerformance(file);
    setRecording(false);
  }
  async function recordAudio() {
    setError("");
    if (recording) {
      await stopAudio();
      return;
    }
    setConnecting(true);
    try {
      if (!navigator.mediaDevices?.getUserMedia)
        throw Error(
          "Microphone recording is unavailable. Use localhost or HTTPS, or upload a WAV file.",
        );
      const stream = await permissionRequest(
        navigator.mediaDevices.getUserMedia({ audio: true }),
        "Microphone permission is still pending. Allow it in your browser, then try again.",
        15000,
        (value) => value.getTracks().forEach((track) => track.stop()),
      );
      recorder.current = await startAudioRecording(stream);
      setRecording(true);
      audioTimer.current = setTimeout(stopAudio, 119000);
    } catch (error) {
      setError(
        error.name === "NotAllowedError"
          ? "Microphone access was denied. Allow it in browser settings or upload a WAV file."
          : error.message,
      );
    } finally {
      setConnecting(false);
    }
  }
  async function connectMidi() {
    setError("");
    setConnecting(true);
    setMidiDevice("");
    try {
      if (!navigator.requestMIDIAccess)
        throw Error(
          "This browser does not support MIDI. Use Chrome or Edge on localhost, or upload a MIDI file.",
        );
      const access = await permissionRequest(
        navigator.requestMIDIAccess(),
        "MIDI permission is still pending. Allow it in your browser, then reconnect.",
      );
      const devices = [...access.inputs.values()].filter(
        (device) => device.state !== "disconnected",
      );
      if (!devices.length)
        throw Error(
          "No MIDI keyboard was found. Connect it by USB and try again.",
        );
      midiAccess.current = access;
      setMidiDevice(devices.map((device) => device.name).join(", "));
    } catch (error) {
      setError(
        error.name === "NotAllowedError"
          ? "MIDI access was denied. Allow it in browser settings or upload a MIDI file."
          : error.message,
      );
    } finally {
      setConnecting(false);
    }
  }
  async function toggleMidi() {
    setError("");
    if (!capturing.current) {
      if (
        ![...midiAccess.current.inputs.values()].some(
          (device) => device.state !== "disconnected",
        )
      ) {
        setError("The keyboard disconnected. Reconnect it before recording.");
        return;
      }
      midiCapture.current = startMidiCapture(
        midiAccess.current,
        setCaptureCount,
      );
      setCaptureCount(0);
      capturing.current = true;
      setRecording(true);
      midiTimer.current = setTimeout(toggleMidi, 119000);
      return;
    }
    clearTimeout(midiTimer.current);
    capturing.current = false;
    setRecording(false);
    const notes = midiCapture.current.stop();
    midiCapture.current = null;
    if (!notes.length) {
      setError("No MIDI notes were recorded. Play a few notes and try again.");
      return;
    }
    setBusy(true);
    setNotice("");
    try {
      let score;
      if (reference) {
        const form = new FormData();
        form.append("reference", reference);
        score = await request("/api/reference", { method: "POST", body: form });
      } else score = await request("/api/reference");
      setResult(
        await request("/api/capture", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            reference: score.notes,
            performance: notes,
            measures: score.measures,
            meter_assumed: score.meter_assumed,
          }),
        }),
      );
      setSelected(null);
    } catch (error) {
      setError(error.message);
    } finally {
      setBusy(false);
    }
  }
  function listen() {
    if (playing) {
      if (audioCtx.current?.state !== "closed") audioCtx.current?.close();
      setPlaying(false);
      return;
    }
    const ctx = new AudioContext();
    audioCtx.current = ctx;
    const events = result?.reference || demoReference;
    events.forEach((n) => {
      const oscillator = ctx.createOscillator(),
        gain = ctx.createGain();
      oscillator.type = "triangle";
      oscillator.frequency.value = 440 * 2 ** ((n.pitch - 69) / 12);
      oscillator.connect(gain);
      gain.connect(ctx.destination);
      gain.gain.setValueAtTime(0, ctx.currentTime + n.start);
      gain.gain.linearRampToValueAtTime(0.13, ctx.currentTime + n.start + 0.01);
      gain.gain.exponentialRampToValueAtTime(
        0.001,
        ctx.currentTime + n.start + n.duration,
      );
      oscillator.start(ctx.currentTime + n.start);
      oscillator.stop(ctx.currentTime + n.start + n.duration + 0.05);
    });
    setPlaying(true);
    setTimeout(
      () => {
        if (audioCtx.current === ctx) {
          if (ctx.state !== "closed") ctx.close();
          setPlaying(false);
        }
      },
      (Math.max(...events.map((n) => n.start + n.duration)) + 0.2) * 1000,
    );
  }
  function exportReport() {
    const url = URL.createObjectURL(
      new Blob([JSON.stringify(result, null, 2)], { type: "application/json" }),
    );
    setExportUrl(url);
    reportDialog.current.showModal();
  }

  return (
    <div className="shell">
      <dialog ref={reportDialog} className="report-dialog">
        <h2>Report JSON</h2>
        <p>Download the file, or select and copy the text below.</p>
        <textarea
          aria-label="Report JSON"
          readOnly
          value={result ? JSON.stringify(result, null, 2) : ""}
        />
        <div className="header-actions">
          <button
            className="button secondary"
            onClick={() =>
              reportDialog.current.querySelector("textarea").select()
            }
          >
            Select JSON
          </button>
          <a
            className="button primary"
            href={exportUrl}
            download="cadence-practice-report.json"
          >
            Download JSON
          </a>
          <button
            className="button secondary"
            onClick={() => reportDialog.current.close()}
          >
            Close report
          </button>
        </div>
      </dialog>
      <aside className="sidebar">
        <div className="brand">
          <span className="brand-icon">
            <Piano size={23} />
          </span>
          cadence<span className="brand-dot">.</span>
        </div>
        <div className="workspace-label">PIANO PRACTICE</div>
        <button
          className={`nav-item ${tab === "overview" ? "active" : ""}`}
          onClick={() => setTab("overview")}
        >
          <Music2 size={18} />
          Results
        </button>
        <button
          className={`nav-item ${tab === "details" ? "active" : ""}`}
          onClick={() => setTab("details")}
        >
          <Table2 size={18} />
          Note table
        </button>
        <div className="sidebar-bottom">
          <div className="tiny-piano">
            {Array.from({ length: 14 }, (_, i) => (
              <i
                key={i}
                className={
                  [1, 2, 4, 5, 6, 8, 9, 11, 12, 13].includes(i)
                    ? "has-black"
                    : ""
                }
              />
            ))}
          </div>
          <p>MIDI and audio analysis</p>
          <button
            className="text-button"
            onClick={() => {
              setInfo(!info);
              window.scrollTo({ top: 0, behavior: "smooth" });
            }}
          >
            <CircleHelp size={15} /> How it works
          </button>
        </div>
      </aside>
      <main>
        <header>
          <div className="breadcrumb">
            <span>Cadence / Piano practice coach</span>
          </div>
          <div className="header-actions">
            <button
              className="text-button"
              onClick={() => setInfo(!info)}
              aria-expanded={info}
            >
              <CircleHelp size={15} />
              How it works
            </button>
            <button
              className="button secondary"
              onClick={() => setTheme(theme === "dark" ? "light" : "dark")}
              aria-label={
                theme === "dark"
                  ? "Switch to light mode"
                  : "Switch to dark mode"
              }
            >
              {theme === "dark" ? <Sun size={16} /> : <Moon size={16} />}
            </button>
          </div>
        </header>
        <div className="page-heading">
          <div>
            <div className="eyebrow">MIDI / AUDIO</div>
            <h1>Piano practice report</h1>
            <p>Compare a take with a reference MIDI.</p>
          </div>
          <button
            className="button secondary"
            disabled={!result}
            onClick={exportReport}
          >
            <Download size={16} />
            Export report
          </button>
        </div>
        {info && (
          <div className="notice">
            Cadence compares your take with a MIDI reference using sequence
            alignment. Timing is measured after removing start delay and overall
            tempo differences. MIDI supports chords; audio estimates one pitch
            per onset and works best with single-note passages. Bar numbers come
            from the reference MIDI. Rules give suggestions by default; local or
            hosted models are optional.
          </div>
        )}
        {notice && (
          <div role="status" className="notice">
            {notice}
          </div>
        )}
        {busy && (
          <div role="status" className="loading-state">
            <span className="spinner" />
            Analyzing the take. Audio may take a minute on the first run.
          </div>
        )}
        {result && (
          <section className="session-banner">
            <div className="session-art">
              <Music2 size={38} />
              <span>♪</span>
            </div>
            <div className="session-copy">
              <div className="eyebrow">
                {result.source === "demo"
                  ? "Demo results"
                  : "Uploaded performance"}
              </div>
              <h2>
                {result.source === "demo"
                  ? "C major exercise"
                  : "Performance results"}
              </h2>
              <p>
                {result.reference_count} reference notes<span>·</span>
                {result.source === "audio"
                  ? "Audio estimate"
                  : result.source === "demo"
                    ? "120 BPM reference"
                    : "MIDI events"}
                <span>·</span>
                {result.source === "demo"
                  ? "~16 seconds"
                  : "Tempo-normalized timing"}
              </p>
            </div>
            <button className="button dark" onClick={listen}>
              {playing ? <Square size={15} /> : <Play size={15} />}
              {playing ? "Stop playback" : "Play reference"}
            </button>
          </section>
        )}
        <div className="content-grid">
          <div className="analysis-column">
            {result ? (
              <>
                <Results
                  result={result}
                  tab={tab}
                  setTab={setTab}
                  selected={selected}
                  setSelected={setSelected}
                />
                <button
                  className="text-button"
                  disabled={busy || recording || connecting}
                  onClick={() => {
                    setResult(null);
                    setSelected(null);
                  }}
                >
                  <Trash2 size={14} />
                  Clear results
                </button>
              </>
            ) : (
              <section className="card empty-state">
                <Music2 size={28} />
                <h3>No results yet</h3>
                <p>
                  Upload a reference MIDI and a take, or open the sample demo.
                </p>
                <button className="button primary" onClick={runDemo}>
                  Quick demo
                </button>
              </section>
            )}
          </div>
          <aside className="upload-column">
            <section className="card upload-card">
              <div className="card-heading">
                <div>
                  <h3>Analyze a take</h3>
                  <p>Choose files or record here.</p>
                </div>
                <span className="upload-icon">
                  <Upload size={18} />
                </span>
              </div>
              <div className="input-switch">
                {[
                  ["midi", Piano, "MIDI"],
                  ["audio", Mic, "Audio"],
                  ["live", Cable, "Keyboard"],
                ].map(([key, Icon, label]) => (
                  <button
                    key={key}
                    disabled={recording || busy || connecting}
                    className={mode === key ? "selected" : ""}
                    onClick={() => {
                      setMode(key);
                      setPerformance(null);
                      setError("");
                    }}
                  >
                    <Icon size={15} />
                    {label}
                  </button>
                ))}
              </div>
              {mode === "live" ? (
                <div className="live-panel">
                  <div className="connection-icon">
                    <Cable size={28} />
                  </div>
                  <h4>{midiDevice || "Connect your keyboard"}</h4>
                  <p>
                    Play the demo exercise, or select your own reference MIDI
                    below. Stop recording to analyze the captured notes.
                  </p>
                  <label className="dropzone">
                    <Music2 size={18} />
                    <strong>
                      {reference?.name || "Optional reference MIDI"}
                    </strong>
                    <small>No file selected: use the demo</small>
                    <input
                      aria-label="Keyboard reference MIDI"
                      type="file"
                      accept=".mid,.midi"
                      disabled={recording || busy || connecting}
                      onChange={(e) => setReference(e.target.files[0])}
                    />
                  </label>
                  <button
                    className="button secondary full"
                    onClick={connectMidi}
                    disabled={recording || busy || connecting}
                  >
                    {connecting
                      ? "Waiting for MIDI permission..."
                      : "Connect MIDI keyboard"}
                  </button>
                  {midiDevice && (
                    <button
                      className="button primary full"
                      disabled={busy || connecting}
                      onClick={toggleMidi}
                    >
                      {recording ? <Square size={15} /> : <Play size={15} />}{" "}
                      {recording
                        ? `Stop & analyze (${captureCount} notes)`
                        : "Record a take"}
                    </button>
                  )}
                </div>
              ) : (
                <form onSubmit={analyzeUpload}>
                  <label className="field-label">
                    01 <span>Reference score</span>
                    <small>MIDI</small>
                  </label>
                  <label className="dropzone">
                    <Music2 size={21} />
                    <strong>
                      {reference?.name || "Choose a reference MIDI"}
                    </strong>
                    <small>.mid or .midi</small>
                    <input
                      type="file"
                      aria-label="Reference MIDI"
                      disabled={busy || recording || connecting}
                      accept=".mid,.midi"
                      onChange={(e) => setReference(e.target.files[0])}
                    />
                  </label>
                  <label className="field-label">
                    02 <span>Your performance</span>
                    <small>{mode === "midi" ? "MIDI" : "AUDIO"}</small>
                  </label>
                  <label className="dropzone">
                    <Upload size={21} />
                    <strong>
                      {performance?.name ||
                        `Choose ${mode === "midi" ? "your MIDI take" : "an audio recording"}`}
                    </strong>
                    <small>
                      {mode === "midi"
                        ? ".mid or .midi"
                        : ".wav, .flac or .ogg"}{" "}
                      · max 20 MB
                    </small>
                    <input
                      type="file"
                      key={mode}
                      aria-label="Performance file"
                      disabled={busy || recording || connecting}
                      accept={
                        mode === "midi" ? ".mid,.midi" : ".wav,.flac,.ogg"
                      }
                      onChange={(e) => setPerformance(e.target.files[0])}
                    />
                  </label>
                  {mode === "audio" && (
                    <button
                      type="button"
                      disabled={busy || connecting}
                      className={
                        "record-button " + (recording ? "is-recording" : "")
                      }
                      onClick={recordAudio}
                    >
                      {recording ? <Square size={14} /> : <Mic size={14} />}{" "}
                      {recording
                        ? "Stop recording"
                        : connecting
                          ? "Waiting for microphone permission..."
                          : "Record microphone"}
                    </button>
                  )}
                  <button
                    className="button primary full"
                    disabled={busy || recording || connecting}
                    type="submit"
                  >
                    {busy ? "Analyzing..." : "Analyze performance"}
                    {!busy && <ArrowUpRight size={17} />}
                  </button>
                </form>
              )}
              {error && (
                <div role="alert" className="error">
                  {error}
                </div>
              )}
              <div className="privacy-note">
                <Check size={13} />
                <span>
                  Files are deleted after analysis.
                  <br />
                  Model suggestions use a short error summary.
                </span>
              </div>
              <div className="sample-downloads">
                <span>SAMPLE FILES</span>
                <a href="/samples/reference.mid" download>
                  Reference MIDI
                </a>
                <a href="/samples/performance.mid" download>
                  MIDI take
                </a>
                <a href="/samples/performance.wav" download>
                  Audio take
                </a>
              </div>
              {mode === "audio" && (
                <p className="audio-note">
                  Audio results are estimates. Use single-note passages in a
                  quiet room. Chords or pedal can confuse pitch tracking.
                  Maximum length: 2 minutes.
                </p>
              )}
            </section>
            <section className="demo-card">
              <span className="eyebrow">SAMPLE DATA</span>
              <h3>Quick demo</h3>
              <p>
                A short C major exercise with timing and pitch errors. No files
                needed.
              </p>
              <button
                className="button primary full"
                disabled={busy || recording || connecting}
                onClick={runDemo}
              >
                Quick demo <ArrowUpRight size={16} />
              </button>
              <div className="demo-wave">
                {Array.from({ length: 40 }, (_, i) => (
                  <i
                    key={i}
                    style={{
                      height: 12 + Math.abs(Math.sin(i * 1.7)) * 32 + "px",
                    }}
                  />
                ))}
              </div>
            </section>
          </aside>
        </div>
        <footer>
          <span>Cadence / React + Python</span>
          <span>Pitch and timing analysis</span>
        </footer>
      </main>
    </div>
  );
}
createRoot(document.getElementById("root")).render(<App />);
